## Tensor

In [2]:
import tensorflow as tf

a = tf.constant("hello world!")
print(a)

print(tf.executing_eagerly())  # Check if eager execution is enabled (should be True by default)

# No need to create a session and run the operation
print(a.numpy())  # Use .numpy() to access the value of the TensorFlow tensor 

tf.Tensor(b'hello world!', shape=(), dtype=string)
True
b'hello world!'


## Constants

In [3]:
print (tf.constant("hello world!"))
print (tf.constant(1))
print (tf.constant(1, tf.int16))
print (tf.constant(1.25))
print (tf.constant([1,2,3]))
print (tf.constant([[1,2,3],[4,5,6]]))
print (tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[13,14,15],[16,17,18]]]))
print (tf.constant([True, True, False]))
print (tf.zeros(10))
print (tf.ones([10, 10]))

tf.Tensor(b'hello world!', shape=(), dtype=string)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int16)
tf.Tensor(1.25, shape=(), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


## Properties

In [6]:
import tensorflow as tf

a = tf.constant(1, name="a")
b = tf.constant(2, name="b")
c = tf.constant(1, name="value")
print(a)
print(b)
print(c)

d = tf.constant([[1, 2], [3, 4], [5, 6]])
e = tf.ones(d.shape[0])
print(a.shape)
print(d.shape)
print(e.shape)

c = tf.constant(1.25)
print(c.dtype)
print(tf.cast(c, dtype=tf.int32).dtype)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
()
(3, 2)
(3,)
<dtype: 'float32'>
<dtype: 'int32'>


## Operators

In [8]:
import tensorflow as tf

a = tf.constant(121.5)
b = tf.constant([[1, 2], [3, 4], [5, 6]])
c = tf.constant([[7, 8], [9, 10], [11, 12]])

r1 = tf.sqrt(a)
r2 = tf.add(b, c)
r3 = tf.multiply(b, c)

print(r1.numpy())
print(r2.numpy())
print(r3.numpy())

11.022704
[[ 8 10]
 [12 14]
 [16 18]]
[[ 7 16]
 [27 40]
 [55 72]]


## Variables

In [10]:
import tensorflow as tf

a = tf.Variable(tf.random.normal([3, 3]), name="v3")
b = tf.Variable([[3, 3], [4, 4]], name="v4")

x = tf.Variable(1)
y = tf.constant(2)
r = tf.multiply(x, y)
x.assign(r)

print(a.numpy())
print(b.numpy())
for i in range(10):
    print(r.numpy())

[[-0.50940204 -0.26123968  1.298192  ]
 [-0.661243    0.19123912 -0.34324405]
 [-0.32498598 -0.46825248  0.36782798]]
[[3 3]
 [4 4]]
2
2
2
2
2
2
2
2
2
2


## Placeholder

In [13]:
import tensorflow as tf
import numpy as np

x = tf.constant([100.0])
z = tf.constant(2.0)
y = x * z

print(x)
print(y.numpy())
print((x * z).numpy())
print((np.random.rand(1, 10) * z).numpy())
print((tf.pow(x, 2)).numpy())

tf.Tensor([100.], shape=(1,), dtype=float32)
[200.]
[200.]
[[0.68397033 0.9478255  0.9933734  0.41895747 1.243973   0.8272608
  0.77046525 0.9326971  1.0912924  0.5519603 ]]
[10000.]


## Tensorboard

In [18]:
import tensorflow as tf

x1 = tf.Variable([5], dtype=tf.int32, name="a")
y1 = tf.Variable([6], dtype=tf.int32, name="b")
c = tf.constant([5], name="c")
f = tf.multiply(x1, y1) + tf.pow(x1, 2) + y1 + c

tf.summary.scalar('f', f[0])

tf.compat.v1.disable_eager_execution()  # Disabling eager execution

with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    summary_writer = tf.compat.v1.summary.FileWriter('tensorboard_example', sess.graph)
    print(sess.run(f))

[66]
